package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"

	"kissengine-bitboard/engine"
)

// pieceTypeNames are the engine's piece type constants, indexed by piece type.
var pieceTypeNames = [...]string{"Pawn", "Rook", "Knight", "Bishop", "Queen", "King"}

// writeParams writes the tuned weights and the measured piece values as the
// generated file engine/eval_params.go. tunedWeights maps a weight name to
// {middlegame, endgame}; header is extra comment text (may be empty).
func writeParams(path string, w [][2]int, pieceValues [7]int, header string) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by tools/texel; DO NOT EDIT.\n\npackage engine\n\n")
	b.WriteString("// tunedWeights overrides the initial values of evalWeights by WeightName, as\n")
	b.WriteString("// {middlegame, endgame}. Regenerate with: go run ./tools/texel\n")
	if header != "" {
		fmt.Fprintf(&b, "//\n// %s\n", header)
	}
	b.WriteString("var tunedWeights = map[string]weight{\n")
	for i, v := range w {
		fmt.Fprintf(&b, "\t%q: {%d, %d},\n", engine.WeightName(i), v[0], v[1])
	}
	b.WriteString("}\n\n")

	b.WriteString("// pieceValues are the piece values SEE and move ordering use, written by\n")
	b.WriteString("// tools/texel as the average change of Evaluate when one piece of that type is\n")
	b.WriteString("// removed. They are not evalWeights (a piece's worth in the evaluation also\n")
	b.WriteString("// depends on where it stands, on the phase and on the mobility and pair\n")
	b.WriteString("// bonuses), but the same numbers Evaluate produces, measured.\n")
	b.WriteString("var pieceValues = [7]int{\n")
	for pt, name := range pieceTypeNames {
		fmt.Fprintf(&b, "\t%s: %d,\n", name, pieceValues[pt])
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(path, src, 0o644)
}

// existingPieceValues reads the pieceValues block of an existing generated
// file. ok is false if the file or the block (all five piece types) is missing.
func existingPieceValues(path string) (values [7]int, ok bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return values, false
	}

	block := regexp.MustCompile(`(?s)var pieceValues = \[7\]int\{(.*?)\n\}`).FindSubmatch(data)
	if block == nil {
		return values, false
	}

	found := 0
	for pt, name := range pieceTypeNames {
		m := regexp.MustCompile(`\b` + name + `:\s*(\d+),`).FindSubmatch(block[1])
		if m == nil {
			continue
		}
		v, err := strconv.Atoi(string(m[1]))
		if err != nil {
			return values, false
		}
		values[pt] = v
		found++
	}

	return values, found == len(pieceTypeNames)
}

// existingHeader returns the "Tuned on ..." comment line of an existing
// generated file (without the leading "// "), or "" if there is none, so that a
// run that only re-measures the piece values keeps the description of the
// tuning that produced the weights.
func existingHeader(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}

	for _, line := range bytes.Split(data, []byte{'\n'}) {
		if rest, ok := bytes.CutPrefix(line, []byte("// Tuned on ")); ok {
			return "Tuned on " + string(rest)
		}
	}

	return ""
}
