package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"

	"kissengine-bitboard/engine"
)

// writeParams writes the tuned weights as the generated file
// engine/eval_params.go: a map from weight name to {middlegame, endgame}.
func writeParams(path string, w [][2]int, header string) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by tools/texel; DO NOT EDIT.\n\npackage engine\n\n")
	fmt.Fprintf(&b, "// tunedWeights overrides the initial values of evalWeights by WeightName, as\n")
	fmt.Fprintf(&b, "// {middlegame, endgame}. Regenerate with: go run ./tools/texel\n//\n// %s\n", header)
	b.WriteString("var tunedWeights = map[string]weight{\n")
	for i, v := range w {
		fmt.Fprintf(&b, "\t%q: {%d, %d},\n", engine.WeightName(i), v[0], v[1])
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(path, src, 0o644)
}
